In [1]:
import pandas as pd
in_path = "/home/xuan/BioinformaticTools/16s/shahid/all_tasks/Different_Time_Points/P11_COLON_WT_HomoHET/P11_COLON_WT_HomoHET.csv"
out_path = "/home/xuan/BioinformaticTools/16s/shahid/all_tasks/Different_Time_Points/P11_COLON_WT_HomoHET/P11_COLON_WT_HomoHET_NEC.csv"
# Read the CSV file into a pandas DataFrame
df = pd.read_csv(in_path)
# print(df)
column_name = 'Experiment'
value_to_filter = 'C'

# Create a new DataFrame without the desired rows
filtered_df = df[df[column_name] != value_to_filter]
print(filtered_df)
# # Save the modified DataFrame back to a CSV file
# df.to_csv('modified_file.csv', index=False)

def filter_element(column_name,value_to_filter,in_path,out_path):
    df = pd.read_csv(in_path)
    # Create a new DataFrame without the desired rows
    filtered_df = df[df[column_name] != value_to_filter]
    filtered_df.to_csv(out_path, index=False)
    return None
filter_element(column_name,value_to_filter,in_path,out_path)
C_out_path = "/home/xuan/BioinformaticTools/16s/shahid/all_tasks/Different_Time_Points/P11_COLON_WT_HomoHET/P11_COLON_WT_HomoHET_C.csv"
filter_element('Experiment',"NEC",in_path,C_out_path)

   #NAME Experiment Tissue type    DOL      Genotype
3   053A        NEC       colon  DOL11  Sig Homo_HET
4   054A        NEC       colon  DOL11  Sig Homo_HET
5   055A        NEC       colon  DOL11  Sig Homo_HET
6   056A        NEC       colon  DOL11  Sig Homo_HET
7   057A        NEC       colon  DOL11  Sig Homo_HET
11  061A        NEC       colon  DOL11  Sig Homo_HET
12  062A        NEC       colon  DOL11  Sig Homo_HET
13  063A        NEC       colon  DOL11  Sig Homo_HET
18  068A        NEC       colon  DOL11  Sig Homo_HET
19  069A        NEC       colon  DOL11  Sig Homo_HET
20  070A        NEC       colon  DOL11  Sig Homo_HET
21  071A        NEC       colon  DOL11        Sig WT
22  072A        NEC       colon  DOL11  Sig Homo_HET
27  077A        NEC       colon  DOL11        Sig WT
28  078A        NEC       colon  DOL11  Sig Homo_HET
29  079A        NEC       colon  DOL11  Sig Homo_HET
39  089A        NEC       colon  DOL11  Sig Homo_HET
40  090A        NEC       colon  DOL11  Sig Homo_HET
41  091A        NEC       colon  DOL11        Sig WT
42  092A        NEC       colon  DOL11  Sig Homo_HET
43  093A        NEC       colon  DOL11        Sig WT
44  094A        NEC       colon  DOL11  Sig Homo_HET
48  098A        NEC       colon  DOL11  Sig Homo_HET
49  099A        NEC       colon  DOL11  Sig Homo_HET
50  100A        NEC       colon  DOL11        Sig WT
51  101A        NEC       colon  DOL11        Sig WT
61  217A        NEC       colon  DOL11  Sig Homo_HET
62  218A        NEC       colon  DOL11        Sig WT
63  219A        NEC       colon  DOL11        Sig WT
64  220A        NEC       colon  DOL11        Sig WT
65  221A        NEC       colon  DOL11  Sig Homo_HET
66  222A        NEC       colon  DOL11  Sig Homo_HET
67  223A        NEC       colon  DOL11  Sig Homo_HET
68  224A        NEC       colon  DOL11        Sig WT
69  225A        NEC       colon  DOL11  Sig Homo_HET
85  241A        NEC       colon  DOL11  Sig Homo_HET
86  242A        NEC       colon  DOL11        Sig WT
87  243A        NEC       colon  DOL11  Sig Homo_HET
88  244A        NEC       colon  DOL11  Sig Homo_HET
89  245A        NEC       colon  DOL11        Sig WT
90  246A        NEC       colon  DOL11        Sig WT
91  247A        NEC       colon  DOL11  Sig Homo_HET
92  248A        NEC       colon  DOL11        Sig WT

In [2]:
import pandas as pd
otu_path  ="/home/xuan/BioinformaticTools/16s/shahid/all_tasks/Different_Time_Points/P8/genus_table_Umar_P8_MPD.csv"
otu_df = pd.read_csv(otu_path)
print(otu_df)

                                                  #NAME      1      2      3  \
0     Bacteria;Firmicutes;Bacilli;Lactobacillales;La...  79024  68214  75562
1     Bacteria;Proteobacteria;Gammaproteobacteria;En...    112    119     87
2     Bacteria;Proteobacteria;Gammaproteobacteria;Pa...   1437   1060   1513
3     Bacteria;Firmicutes;Bacilli;Bacillales;Staphyl...   1673   3455   3156
4     Bacteria;Firmicutes;Clostridia;Clostridiales;C...      0      0      0
...                                                 ...    ...    ...    ...
1025  Bacteria;Proteobacteria;Gammaproteobacteria;Ps...      0      0      0
1026  Bacteria;Firmicutes;Bacilli;Bacillales;Bacilla...      0      0      0
1027  Bacteria;Proteobacteria;Gammaproteobacteria;Be...      0      0      0
1028  Eukaryota;Euglenozoa;Kinetoplastea;Metakinetop...      0      0      0
1029  Bacteria;Proteobacteria;Alphaproteobacteria;Az...      0      0      0

          4      5      6      7      8      9  ...     40     41     42  \
0      2245   5772   1801  76450  67741  10408  ...  43122  61382  58837
1     71463  61929  53539   1279     66  51014  ...  35024  16635  25931
2        65   2354    571   1236   2123    355  ...    326    750    445
3      1148   7138    521      9     13   5367  ...     24     26     29
4         4      0      0      0      0      0  ...      0      0      0
...     ...    ...    ...    ...    ...    ...  ...    ...    ...    ...
1025      0      0      0      0      0      0  ...      0      0      0
1026      0      0      0      0      0      0  ...      0      0      0
1027      0      0      0      0      0      0  ...      0      0      0
1028      0      0      0      0      0      0  ...      0      0      0
1029      0      0      0      0      0      0  ...      2      0      0

         43     44     45     46     47     48     49
0     45099  28817   7736  40495  43195  65386  60506
1     37296  43993  83687  31345  35563   4529  14154
2       286    110    174    552    635   2600   1250
3        29    211     93      0      0      0      0
4         0      0      0      0      0      0      0
...     ...    ...    ...    ...    ...    ...    ...
1025      0      0      0      0      0      0      0
1026      0      0      0      0      0      0      0
1027      0      0      0      0      0      0      0
1028      0      0      0      0      0      0      0
1029      0      0      0      0      0      0      0

[1030 rows x 49 columns]

In [3]:
grp_path  ="/home/xuan/BioinformaticTools/16s/shahid/all_tasks/Different_Time_Points/P8/P8_C.csv"
grp_df = pd.read_csv(grp_path)
# List of column names to keep
first_column_list = grp_df.iloc[:, 0].astype(str).tolist()
print(first_column_list)
# Filter the DataFrame to keep only the desired columns
fina_df = otu_df.filter(["#NAME"]+first_column_list)
print(fina_df)

def rebuild_otu(otu_path,grp_path,out_path):
    otu_df = pd.read_csv(otu_path)
    grp_df = pd.read_csv(grp_path)
    first_column_list = grp_df.iloc[:, 0].astype(str).tolist()
    fina_df = otu_df.filter(["#NAME"]+first_column_list)
    fina_df.to_csv(out_path, index=False)
    grp_df.to_csv(grp_path, index=False)
    print(fina_df)
    return None

['1', '2', '3', '7', '8', '11', '12', '13', '14', '15', '22', '23', '24', '25', '30', '40', '41', '42', '43', '46', '47', '48', '49']
                                                  #NAME      1      2      3  \
0     Bacteria;Firmicutes;Bacilli;Lactobacillales;La...  79024  68214  75562
1     Bacteria;Proteobacteria;Gammaproteobacteria;En...    112    119     87
2     Bacteria;Proteobacteria;Gammaproteobacteria;Pa...   1437   1060   1513
3     Bacteria;Firmicutes;Bacilli;Bacillales;Staphyl...   1673   3455   3156
4     Bacteria;Firmicutes;Clostridia;Clostridiales;C...      0      0      0
...                                                 ...    ...    ...    ...
1025  Bacteria;Proteobacteria;Gammaproteobacteria;Ps...      0      0      0
1026  Bacteria;Firmicutes;Bacilli;Bacillales;Bacilla...      0      0      0
1027  Bacteria;Proteobacteria;Gammaproteobacteria;Be...      0      0      0
1028  Eukaryota;Euglenozoa;Kinetoplastea;Metakinetop...      0      0      0
1029  Bacteria;Proteobacteria;Alphaproteobacteria;Az...      0      0      0

          7      8     11     13     14     15  ...     25     30     40  \
0     76450  67741  50388  47940  42325  47632  ...  64370  34297  43122
1      1279     66  27599  40019  33129  33063  ...  27650  14280  35024
2      1236   2123    341   1421    420    560  ...    234    377    326
3         9     13    115    388     91     92  ...     29      0     24
4         0      0      0      0      0      0  ...      0      0      0
...     ...    ...    ...    ...    ...    ...  ...    ...    ...    ...
1025      0      0      0      0      0      0  ...      0      0      0
1026      0      0      0      0      0      0  ...      0      0      0
1027      0      0      0      0      0      0  ...      0      0      0
1028      0      0      0      0      0      0  ...      0      0      0
1029      0      0      0      0      0      0  ...      0      0      2

         41     42     43     46     47     48     49
0     61382  58837  45099  40495  43195  65386  60506
1     16635  25931  37296  31345  35563   4529  14154
2       750    445    286    552    635   2600   1250
3        26     29     29      0      0      0      0
4         0      0      0      0      0      0      0
...     ...    ...    ...    ...    ...    ...    ...
1025      0      0      0      0      0      0      0
1026      0      0      0      0      0      0      0
1027      0      0      0      0      0      0      0
1028      0      0      0      0      0      0      0
1029      0      0      0      0      0      0      0

[1030 rows x 23 columns]

In [6]:
# rebuild_otu(otu_path,grp_path,out_path)
path_otu = "./P8/genus_table_Umar_P8_MPD.csv"
grp_path = "./P8/P8_WT.csv"
out_otu_path = "./P8/genus_table_P8_WT.csv"
rebuild_otu(path_otu,grp_path,out_otu_path)

path_otu = "./P8/genus_table_Umar_P8_MPD.csv"
grp_path = "./P8/P8_Homo.csv"
out_otu_path = "./P8/genus_table_P8_Homo.csv"
rebuild_otu(path_otu,grp_path,out_otu_path)

path_otu = "./P8/genus_table_Umar_P8_MPD.csv"
grp_path = "./P8/P8_HET.csv"
out_otu_path = "./P8/genus_table_P8_HET.csv"
rebuild_otu(path_otu,grp_path,out_otu_path)

                                                  #NAME      2      5     10  \
0     Bacteria;Firmicutes;Bacilli;Lactobacillales;La...  68214   5772   4422
1     Bacteria;Proteobacteria;Gammaproteobacteria;En...    119  61929  67843
2     Bacteria;Proteobacteria;Gammaproteobacteria;Pa...   1060   2354   1972
3     Bacteria;Firmicutes;Bacilli;Bacillales;Staphyl...   3455   7138   8590
4     Bacteria;Firmicutes;Clostridia;Clostridiales;C...      0      0      0
...                                                 ...    ...    ...    ...
1025  Bacteria;Proteobacteria;Gammaproteobacteria;Ps...      0      0      0
1026  Bacteria;Firmicutes;Bacilli;Bacillales;Bacilla...      0      0      0
1027  Bacteria;Proteobacteria;Gammaproteobacteria;Be...      0      0      0
1028  Eukaryota;Euglenozoa;Kinetoplastea;Metakinetop...      0      0      0
1029  Bacteria;Proteobacteria;Alphaproteobacteria;Az...      0      0      0

         11     18     20     22     25     27     32     36     39     40  \
0     50388  12182  26764  41778  64370   3013  15614  49692  62759  43122
1     27599  66195  48051  31022  27650  71081  51739    119    149  35024
2       341     99     61    975    234    158     94   8648   5376    326
3       115    980    830     42     29   1357     17  15130   1623     24
4         0      0      0      0      0      0      0      0      0      0
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
1025      0      0      0      0      0      0      0      0      0      0
1026      0      0      0      0      0      0      0      0      0      0
1027      0      0      0      0      0      0      0      0      0      0
1028      0      0      0      0      0      0      0      0      0      0
1029      0      0      0      0      0      0      0      0      0      2

         44     46
0     28817  40495
1     43993  31345
2       110    552
3       211      0
4         0      0
...     ...    ...
1025      0      0
1026      0      0
1027      0      0
1028      0      0
1029      0      0

[1030 rows x 16 columns]
                                                  #NAME      1      4      7  \
0     Bacteria;Firmicutes;Bacilli;Lactobacillales;La...  79024   2245  76450
1     Bacteria;Proteobacteria;Gammaproteobacteria;En...    112  71463   1279
2     Bacteria;Proteobacteria;Gammaproteobacteria;Pa...   1437     65   1236
3     Bacteria;Firmicutes;Bacilli;Bacillales;Staphyl...   1673   1148      9
4     Bacteria;Firmicutes;Clostridia;Clostridiales;C...      0      4      0
...                                                 ...    ...    ...    ...
1025  Bacteria;Proteobacteria;Gammaproteobacteria;Ps...      0      0      0
1026  Bacteria;Firmicutes;Bacilli;Bacillales;Bacilla...      0      0      0
1027  Bacteria;Proteobacteria;Gammaproteobacteria;Be...      0      0      0
1028  Eukaryota;Euglenozoa;Kinetoplastea;Metakinetop...      0      0      0
1029  Bacteria;Proteobacteria;Alphaproteobacteria;Az...      0      0      0

          8     13     16     23     24     29     30     37     41     42  \
0     67741  47940   3447  67241  67961  21695  34297   3436  61382  58837
1        66  40019  72067  31246  29885  65148  14280    876  16635  25931
2      2123   1421    122    423    223     45    377  45475    750    445
3        13    388    743     14     54   1520      0    879     26     29
4         0      0      0      0      0      0      0      0      0      0
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
1025      0      0      0      0      0      0      0      0      0      0
1026      0      0      0      0      0      0      0      0      0      0
1027      0      0      0      0      0      0      0      0      0      0
1028      0      0      0      0      0      0      0      0      0      0
1029      0      0      0      0      0      0      0      0      0      0

         45     47
0      7736  43195
1     83687  35563
2       174    635
3        93      0
4         0      0
...     ...    ...
1025      0      0
1026      0      0
1027      0      0
1028      0      0
1029      0      0

[1030 rows x 16 columns]
                                                  #NAME      3      6      9  \
0     Bacteria;Firmicutes;Bacilli;Lactobacillales;La...  75562   1801  10408
1     Bacteria;Proteobacteria;Gammaproteobacteria;En...     87  53539  51014
2     Bacteria;Proteobacteria;Gammaproteobacteria;Pa...   1513    571    355
3     Bacteria;Firmicutes;Bacilli;Bacillales;Staphyl...   3156    521   5367
4     Bacteria;Firmicutes;Clostridia;Clostridiales;C...      0      0      0
...                                                 ...    ...    ...    ...
1025  Bacteria;Proteobacteria;Gammaproteobacteria;Ps...      0      0      0
1026  Bacteria;Firmicutes;Bacilli;Bacillales;Bacilla...      0      0      0
1027  Bacteria;Proteobacteria;Gammaproteobacteria;Be...      0      0      0
1028  Eukaryota;Euglenozoa;Kinetoplastea;Metakinetop...      0      0      0
1029  Bacteria;Proteobacteria;Alphaproteobacteria;Az...      0      0      0

         14     15     17     19     21     26     28     31     33     34  \
0     42325  47632   1182   4260  14816   7749  10473    362   3891    737
1     33129  33063  52434  72604  63921  61560  55755  71280  59443  78750
2       420    560     80    292    353      9     10     50     31    274
3        91     92    403   1577    256    102   1076     20     37      0
4         0      0      0      0      5      0      0      0      0      0
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
1025      0      0      0      0      0      0      0      0      0      0
1026      0      0      0      0      0      0      0      0      0      0
1027      0      0      0      0      0      0      0      0      0      0
1028      0      0      0      0      0      0      0      0      0      0
1029      0      0      0      0      0      0      0      0      0      0

         35     38     43     48     49
0     40274  68000  45099  65386  60506
1       210    148  37296   4529  14154
2     18649    405    286   2600   1250
3      2550   6475     29      0      0
4         0      0      0      0      0
...     ...    ...    ...    ...    ...
1025      0      0      0      0      0
1026      0      0      0      0      0
1027      0      0      0      0      0
1028      0      0      0      0      0
1029      0      0      0      0      0

[1030 rows x 19 columns]